url: https://minkakao.github.io/c_realTimes/
baseurl: /c_realTimes/

# Site settings
title: 시리얼타임즈 c.realTimes
email: minkaka5@gmail.com
description: "c.realTimes' artworks and projects. "

# Team names, titles and social links
people:
- name: Kim Minkyeung
  pic: 1
  position: Media Artist<br>
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: https://github.com/minkakao/projects

# Postal address (add as many lines as necessary)
address:
  - line: 145-5, Daeheung-ro, Mapo-gu, Seoul
  - line: Republic of Korea

# Build settings
markdown: kramdown
permalink: pretty
